import type { PatternElement } from './types';

/* ═══════════════════════════════════════════════════════════════════════════
   DEFAULT PATTERN ELEMENTS — per use-case template and GTT solution.
   Each array is the canonical set for a given context.  Customer overrides
   are stored separately and merged at render time.
   ═══════════════════════════════════════════════════════════════════════════ */

/* ── On-Demand Connectivity ── */
export const ON_DEMAND_ELEMENTS: PatternElement[] = [
  { id: 'od-orch-portal', label: 'Orchestration Portal', icon: '🎛', category: 'Control', description: 'Self-service portal for provisioning, modifying, and monitoring on-demand connections.', applicability: 'active', quantity: 1, deploymentRole: 'Management Plane', networkType: 'Control / API', securityAttributes: 'RBAC, SSO/SAML, MFA, audit logging', performanceAttributes: 'Sub-second UI response, real-time telemetry', resiliencyAttributes: 'Active-active across regions, 99.99% uptime', managementModel: 'managed', providerModel: 'GTT-operated', implementationPhase: 1, customerNotes: '', x: 300, y: 30, group: 'control' },
  { id: 'od-api-gw', label: 'API Gateway', icon: '🔗', category: 'Control', description: 'RESTful API layer for programmatic provisioning and IaC integration (Terraform, Pulumi).', applicability: 'active', quantity: 1, deploymentRole: 'Integration Layer', networkType: 'API / Webhook', securityAttributes: 'OAuth 2.0, API key rotation, rate limiting', performanceAttributes: '< 200ms API response, async job tracking', resiliencyAttributes: 'Multi-region with automatic failover', managementModel: 'managed', providerModel: 'GTT-operated', implementationPhase: 1, customerNotes: '', x: 300, y: 130, group: 'control' },
  { id: 'od-branch-a', label: 'Branch Site A', icon: '🏢', category: 'Edge', description: 'Representative branch office connected via on-demand NaaS fabric.', applicability: 'active', quantity: 10, deploymentRole: 'Branch / Remote Office', networkType: 'Ethernet / Broadband', securityAttributes: 'IPsec tunnel, firewall policy propagation', performanceAttributes: '50 Mbps – 1 Gbps per site', resiliencyAttributes: 'Dual-path with automatic failover', managementModel: 'co-managed', providerModel: 'GTT underlay + customer CPE', implementationPhase: 2, customerNotes: '', x: 60, y: 250, group: 'edge' },
  { id: 'od-branch-b', label: 'Branch Site B', icon: '🏢', category: 'Edge', description: 'Additional branch site tier for smaller or remote locations.', applicability: 'active', quantity: 25, deploymentRole: 'Branch / Remote Office', networkType: 'Broadband / LTE', securityAttributes: 'IPsec tunnel, local firewall', performanceAttributes: '20 Mbps – 200 Mbps per site', resiliencyAttributes: 'Single-path with LTE backup', managementModel: 'co-managed', providerModel: 'GTT underlay + customer CPE', implementationPhase: 2, customerNotes: '', x: 180, y: 250, group: 'edge' },
  { id: 'od-naas-fabric', label: 'NaaS Fabric', icon: '🌐', category: 'Core', description: 'GTT Tier 1 backbone fabric providing elastic, on-demand connectivity services.', applicability: 'active', quantity: 1, deploymentRole: 'Core Transport', networkType: 'MPLS / SR-MPLS / EVPN', securityAttributes: 'MACsec, per-tenant VRF isolation', performanceAttributes: '50 Mbps – 100 Gbps elastic', resiliencyAttributes: 'Fully meshed core, sub-50ms convergence', managementModel: 'managed', providerModel: 'GTT-owned backbone', implementationPhase: 1, customerNotes: '', x: 300, y: 250, group: 'core' },
  { id: 'od-cloud', label: 'Cloud Region', icon: '☁️', category: 'Cloud', description: 'Direct cloud interconnect to primary CSP (AWS/Azure/GCP).', applicability: 'active', quantity: 2, deploymentRole: 'Cloud On-Ramp', networkType: 'Direct Connect / ExpressRoute', securityAttributes: 'MACsec on interconnect, CSP-native security groups', performanceAttributes: '1 – 10 Gbps dedicated', resiliencyAttributes: 'Diverse paths with BGP failover', managementModel: 'managed', providerModel: 'GTT CloudConnect', implementationPhase: 1, customerNotes: '', x: 420, y: 250, group: 'cloud' },
  { id: 'od-dc', label: 'Data Center', icon: '🏗', category: 'DC', description: 'On-premises or colocation data center connected to the NaaS fabric.', applicability: 'active', quantity: 2, deploymentRole: 'Data Center', networkType: 'Cross-connect / Dark Fiber', securityAttributes: 'Physical security, network segmentation', performanceAttributes: '10 – 100 Gbps dedicated', resiliencyAttributes: 'Dual-homed, active-active', managementModel: 'co-managed', providerModel: 'Customer-owned / Colo + GTT transport', implementationPhase: 1, customerNotes: '', x: 540, y: 250, group: 'dc' },
  { id: 'od-metering', label: 'Metering Engine', icon: '📊', category: 'Control', description: 'Real-time usage metering and cost analytics for consumption-based billing.', applicability: 'optional', quantity: 1, deploymentRole: 'Billing / FinOps', networkType: 'Internal API', securityAttributes: 'Encrypted data at rest, access audit', performanceAttributes: 'Per-minute granularity, real-time dashboards', resiliencyAttributes: 'Replicated storage, 99.99% data durability', managementModel: 'managed', providerModel: 'GTT-operated', implementationPhase: 1, customerNotes: '', x: 480, y: 130, group: 'control' },
];

/* ── Multi-Cloud Connectivity ── */
export const MULTI_CLOUD_ELEMENTS: PatternElement[] = [
  { id: 'mc-orch', label: 'CloudConnect Orchestrator', icon: '🎛', category: 'Control', description: 'Unified management platform for all cloud interconnects and cross-cloud policies.', applicability: 'active', quantity: 1, deploymentRole: 'Management Plane', networkType: 'Control / API', securityAttributes: 'RBAC, SSO, audit trail, MFA', performanceAttributes: 'Real-time topology visualization', resiliencyAttributes: 'Active-active, geo-redundant', managementModel: 'managed', providerModel: 'GTT-operated', implementationPhase: 1, customerNotes: '', x: 300, y: 30, group: 'control' },
  { id: 'mc-aws', label: 'AWS VPC', icon: '☁️', category: 'Cloud', description: 'Amazon Web Services Virtual Private Cloud with Direct Connect interconnect.', applicability: 'active', quantity: 3, deploymentRole: 'Cloud Workloads', networkType: 'Direct Connect (dedicated/hosted)', securityAttributes: 'Security Groups, NACLs, GuardDuty integration', performanceAttributes: '1 – 10 Gbps dedicated interconnect', resiliencyAttributes: 'Multi-AZ, diverse Direct Connect paths', managementModel: 'co-managed', providerModel: 'Customer AWS account + GTT interconnect', implementationPhase: 1, customerNotes: '', x: 80, y: 160, group: 'cloud' },
  { id: 'mc-azure', label: 'Azure VNet', icon: '☁️', category: 'Cloud', description: 'Microsoft Azure Virtual Network with ExpressRoute interconnect.', applicability: 'active', quantity: 2, deploymentRole: 'Cloud Workloads', networkType: 'ExpressRoute (private/Microsoft peering)', securityAttributes: 'NSGs, Azure Firewall, Defender integration', performanceAttributes: '1 – 10 Gbps ExpressRoute circuit', resiliencyAttributes: 'Zone-redundant, Global Reach enabled', managementModel: 'co-managed', providerModel: 'Customer Azure tenant + GTT interconnect', implementationPhase: 1, customerNotes: '', x: 300, y: 160, group: 'cloud' },
  { id: 'mc-gcp', label: 'GCP VPC', icon: '☁️', category: 'Cloud', description: 'Google Cloud Platform VPC with Cloud Interconnect.', applicability: 'future-phase', quantity: 1, deploymentRole: 'Cloud Workloads', networkType: 'Partner/Dedicated Interconnect', securityAttributes: 'Firewall Rules, Cloud Armor, VPC Service Controls', performanceAttributes: '1 – 10 Gbps interconnect', resiliencyAttributes: 'Multi-region, Cloud Router BGP', managementModel: 'co-managed', providerModel: 'Customer GCP project + GTT interconnect', implementationPhase: 2, customerNotes: '', x: 520, y: 160, group: 'cloud' },
  { id: 'mc-fabric', label: 'Interconnect Fabric', icon: '🌐', category: 'Core', description: 'GTT cloud exchange backbone interconnecting all CSPs with optimized routing.', applicability: 'active', quantity: 1, deploymentRole: 'Core Transport', networkType: 'EVPN-VXLAN / SR-MPLS', securityAttributes: 'MACsec encryption, micro-segmentation', performanceAttributes: '< 10ms cross-cloud latency', resiliencyAttributes: 'Fully diverse, automatic path failover', managementModel: 'managed', providerModel: 'GTT-owned fabric', implementationPhase: 1, customerNotes: '', x: 300, y: 280, group: 'core' },
  { id: 'mc-dc', label: 'On-Prem DC', icon: '🏗', category: 'DC', description: 'On-premises data center with hybrid cloud connectivity.', applicability: 'active', quantity: 2, deploymentRole: 'Data Center', networkType: 'Cross-connect / Dedicated fiber', securityAttributes: 'Physical + network segmentation', performanceAttributes: '10 – 100 Gbps', resiliencyAttributes: 'Dual-homed to GTT fabric', managementModel: 'customer-managed', providerModel: 'Customer-owned + GTT transport', implementationPhase: 1, customerNotes: '', x: 120, y: 370, group: 'dc' },
  { id: 'mc-policy', label: 'Policy Engine', icon: '🔒', category: 'Security', description: 'Unified network policy engine translating intent to CSP-native security constructs.', applicability: 'active', quantity: 1, deploymentRole: 'Security Policy', networkType: 'Control Plane', securityAttributes: 'Policy sync, drift detection, compliance reporting', performanceAttributes: 'Real-time policy propagation', resiliencyAttributes: 'Replicated policy store', managementModel: 'managed', providerModel: 'GTT-operated', implementationPhase: 2, customerNotes: '', x: 480, y: 370, group: 'security' },
  { id: 'mc-saas', label: 'SaaS Platforms', icon: '📦', category: 'SaaS', description: 'SaaS application direct breakout optimization (O365, Salesforce, etc).', applicability: 'optional', quantity: 5, deploymentRole: 'SaaS Access', networkType: 'Internet / Direct Peering', securityAttributes: 'CASB integration, DLP policies', performanceAttributes: 'Direct path to SaaS PoPs', resiliencyAttributes: 'Multiple egress points', managementModel: 'managed', providerModel: 'GTT routing optimization', implementationPhase: 2, customerNotes: '', x: 300, y: 370, group: 'saas' },
];

/* ── SD-WAN ── */
export const SDWAN_ELEMENTS: PatternElement[] = [
  { id: 'sd-orch', label: 'SD-WAN Orchestrator', icon: '🎛', category: 'Control', description: 'Centralized orchestrator providing single-pane management for all SD-WAN sites.', applicability: 'active', quantity: 1, deploymentRole: 'Management Plane', networkType: 'Cloud-hosted controller', securityAttributes: 'RBAC, MFA, encrypted management plane', performanceAttributes: 'Real-time site/link/app visibility', resiliencyAttributes: 'HA cluster, geo-redundant', managementModel: 'managed', providerModel: 'GTT NOC-operated', implementationPhase: 1, customerNotes: '', x: 300, y: 20, group: 'control' },
  { id: 'sd-hub', label: 'Hub Gateway', icon: '🏗', category: 'DC', description: 'Hub-site SD-WAN gateway at primary data center or regional hub.', applicability: 'active', quantity: 2, deploymentRole: 'Hub / Aggregation', networkType: 'MPLS + DIA + Broadband', securityAttributes: 'NGFW, IPS, segmentation', performanceAttributes: '1 – 10 Gbps aggregation', resiliencyAttributes: 'Dual-CPE HA, diverse transport', managementModel: 'managed', providerModel: 'GTT managed CPE + transport', implementationPhase: 1, customerNotes: '', x: 300, y: 140, group: 'core' },
  { id: 'sd-branch-1', label: 'Branch CPE — Tier 1', icon: '🏢', category: 'Edge', description: 'Large branch with dual-transport SD-WAN CPE.', applicability: 'active', quantity: 15, deploymentRole: 'Branch / Office', networkType: 'MPLS + Broadband', securityAttributes: 'Integrated firewall, URL filtering', performanceAttributes: '100 Mbps – 1 Gbps', resiliencyAttributes: 'Dual-transport failover', managementModel: 'managed', providerModel: 'GTT managed CPE', implementationPhase: 2, customerNotes: '', x: 60, y: 280, group: 'edge' },
  { id: 'sd-branch-2', label: 'Branch CPE — Tier 2', icon: '🏢', category: 'Edge', description: 'Medium branch with broadband + LTE SD-WAN CPE.', applicability: 'active', quantity: 30, deploymentRole: 'Branch / Office', networkType: 'Broadband + LTE', securityAttributes: 'Integrated firewall, basic IPS', performanceAttributes: '50 – 200 Mbps', resiliencyAttributes: 'Broadband + LTE failover', managementModel: 'managed', providerModel: 'GTT managed CPE', implementationPhase: 2, customerNotes: '', x: 200, y: 280, group: 'edge' },
  { id: 'sd-branch-3', label: 'Branch CPE — Tier 3', icon: '🏢', category: 'Edge', description: 'Small/remote site with single broadband or LTE.', applicability: 'future-phase', quantity: 50, deploymentRole: 'Branch / Remote', networkType: 'Broadband or LTE', securityAttributes: 'Basic firewall, cloud security chaining', performanceAttributes: '20 – 100 Mbps', resiliencyAttributes: 'Single link + cloud-based DR', managementModel: 'managed', providerModel: 'GTT managed CPE', implementationPhase: 3, customerNotes: '', x: 400, y: 280, group: 'edge' },
  { id: 'sd-branch-4', label: 'Retail / Kiosk CPE', icon: '🏪', category: 'Edge', description: 'Retail location or kiosk with lightweight SD-WAN.', applicability: 'not-applicable', quantity: 0, deploymentRole: 'Retail / IoT', networkType: 'Broadband / LTE', securityAttributes: 'Segmentation, restricted access', performanceAttributes: '10 – 50 Mbps', resiliencyAttributes: 'LTE failover', managementModel: 'managed', providerModel: 'GTT managed CPE', implementationPhase: 3, customerNotes: '', x: 540, y: 280, group: 'edge' },
  { id: 'sd-cloud-gw', label: 'Cloud Gateway', icon: '☁️', category: 'Cloud', description: 'Virtual SD-WAN gateway in public cloud for direct workload connectivity.', applicability: 'active', quantity: 2, deploymentRole: 'Cloud On-Ramp', networkType: 'AWS TGW / Azure vWAN', securityAttributes: 'CSP-native + overlay security', performanceAttributes: '1 – 10 Gbps', resiliencyAttributes: 'Multi-AZ deployment', managementModel: 'co-managed', providerModel: 'GTT + customer cloud account', implementationPhase: 2, customerNotes: '', x: 120, y: 140, group: 'cloud' },
  { id: 'sd-saas', label: 'SaaS Breakout', icon: '🌐', category: 'SaaS', description: 'Local internet breakout optimized for SaaS applications.', applicability: 'active', quantity: 1, deploymentRole: 'SaaS Optimization', networkType: 'DIA / Local Breakout', securityAttributes: 'SWG / cloud security chaining', performanceAttributes: 'Direct-to-SaaS path', resiliencyAttributes: 'Multiple breakout points', managementModel: 'managed', providerModel: 'GTT routing policy', implementationPhase: 2, customerNotes: '', x: 480, y: 140, group: 'saas' },
];

/* ── SASE ── */
export const SASE_ELEMENTS: PatternElement[] = [
  { id: 'sa-portal', label: 'SASE Management Portal', icon: '🎛', category: 'Control', description: 'Unified management console for converged SD-WAN + SSE policy.', applicability: 'active', quantity: 1, deploymentRole: 'Management Plane', networkType: 'Cloud-hosted console', securityAttributes: 'RBAC, MFA, SSO/SAML, audit logging', performanceAttributes: 'Real-time security + network dashboards', resiliencyAttributes: 'Global HA, geo-redundant', managementModel: 'managed', providerModel: 'GTT Secure Connect', implementationPhase: 1, customerNotes: '', x: 300, y: 30, group: 'control' },
  { id: 'sa-swg', label: 'Secure Web Gateway', icon: '🌐', category: 'Security', description: 'Cloud-delivered SWG with full TLS 1.3 inspection at line rate.', applicability: 'active', quantity: 1, deploymentRole: 'Security — Web', networkType: 'Cloud SSE PoP', securityAttributes: 'URL filtering, malware scanning, TLS inspection', performanceAttributes: 'Sub-5ms inspection latency', resiliencyAttributes: '150+ PoPs, automatic failover', managementModel: 'managed', providerModel: 'GTT + Zscaler/PAN/Fortinet', implementationPhase: 1, customerNotes: '', x: 120, y: 140, group: 'security' },
  { id: 'sa-ztna', label: 'ZTNA', icon: '🔐', category: 'Security', description: 'Zero Trust Network Access replacing legacy VPN for private application access.', applicability: 'active', quantity: 1, deploymentRole: 'Security — Access', networkType: 'Cloud-brokered tunnels', securityAttributes: 'Identity-centric, device posture, continuous auth', performanceAttributes: 'Direct-to-app, no hairpinning', resiliencyAttributes: 'Global PoP distribution', managementModel: 'managed', providerModel: 'GTT + SSE vendor', implementationPhase: 1, customerNotes: '', x: 260, y: 140, group: 'security' },
  { id: 'sa-casb', label: 'CASB', icon: '📋', category: 'Security', description: 'Cloud Access Security Broker for SaaS visibility, control, and DLP.', applicability: 'optional', quantity: 1, deploymentRole: 'Security — SaaS', networkType: 'Inline + API-based', securityAttributes: 'Shadow IT detection, DLP, access control', performanceAttributes: 'Real-time SaaS monitoring', resiliencyAttributes: 'Multi-tenant cloud service', managementModel: 'managed', providerModel: 'GTT + SSE vendor', implementationPhase: 2, customerNotes: '', x: 400, y: 140, group: 'security' },
  { id: 'sa-fwaas', label: 'FWaaS', icon: '🔥', category: 'Security', description: 'Firewall-as-a-Service with L3-L7 inspection in the cloud.', applicability: 'active', quantity: 1, deploymentRole: 'Security — Firewall', networkType: 'Cloud SSE PoP', securityAttributes: 'NGFW rules, IPS/IDS, threat intelligence', performanceAttributes: 'Line-rate inspection', resiliencyAttributes: 'HA across SSE PoPs', managementModel: 'managed', providerModel: 'GTT + SSE vendor', implementationPhase: 1, customerNotes: '', x: 540, y: 140, group: 'security' },
  { id: 'sa-remote', label: 'Remote Users', icon: '👤', category: 'Edge', description: 'Remote and hybrid workforce connecting through client connector agent.', applicability: 'active', quantity: 500, deploymentRole: 'End User — Remote', networkType: 'Client connector / Agentless', securityAttributes: 'Device posture check, ZTNA policy', performanceAttributes: 'Nearest SSE PoP steering', resiliencyAttributes: 'Automatic PoP failover', managementModel: 'co-managed', providerModel: 'Customer devices + GTT agent', implementationPhase: 1, customerNotes: '', x: 60, y: 280, group: 'edge' },
  { id: 'sa-branch', label: 'Branch SD-WAN Sites', icon: '🏢', category: 'Edge', description: 'Branch offices with SD-WAN CPE steering traffic to SSE cloud.', applicability: 'active', quantity: 30, deploymentRole: 'Branch — SD-WAN', networkType: 'GRE/IPsec to SSE PoP', securityAttributes: 'Tunnel encryption, local segmentation', performanceAttributes: '50 Mbps – 1 Gbps per site', resiliencyAttributes: 'Dual-transport + SSE PoP failover', managementModel: 'managed', providerModel: 'GTT managed CPE + SSE', implementationPhase: 2, customerNotes: '', x: 220, y: 280, group: 'edge' },
  { id: 'sa-saas', label: 'SaaS Applications', icon: '📦', category: 'SaaS', description: 'SaaS applications accessed through SSE inspection and CASB policies.', applicability: 'active', quantity: 15, deploymentRole: 'Application — SaaS', networkType: 'HTTPS / API', securityAttributes: 'CASB inline + API, DLP, access control', performanceAttributes: 'Direct-to-cloud after inspection', resiliencyAttributes: 'Multi-path through SSE', managementModel: 'managed', providerModel: 'SaaS vendor + GTT security', implementationPhase: 2, customerNotes: '', x: 380, y: 280, group: 'saas' },
  { id: 'sa-private', label: 'Private Applications', icon: '🏗', category: 'DC', description: 'On-premises or private cloud applications accessed via ZTNA.', applicability: 'active', quantity: 20, deploymentRole: 'Application — Private', networkType: 'ZTNA app connector', securityAttributes: 'Zero trust, no inbound ports', performanceAttributes: 'Direct tunnel to app', resiliencyAttributes: 'Connector HA pairs', managementModel: 'co-managed', providerModel: 'Customer DC + GTT connector', implementationPhase: 2, customerNotes: '', x: 540, y: 280, group: 'dc' },
];

/** Lookup map keyed by useCaseId (works for both template and GTT views). */
export const PATTERN_ELEMENTS: Record<string, PatternElement[]> = {
  'on-demand': ON_DEMAND_ELEMENTS,
  'multi-cloud': MULTI_CLOUD_ELEMENTS,
  'sdwan': SDWAN_ELEMENTS,
  'sase': SASE_ELEMENTS,
};
