import type { UseCaseTemplate } from './types';

/* ═══════════════════════════════════════════════════════════════════════════
   USE CASE TEMPLATE LIBRARY
   Frozen base templates — never mutated at runtime.
   Customer-specific state (checked items, notes, fit scores, designations)
   is stored separately in the studio hook.
   ═══════════════════════════════════════════════════════════════════════════ */

const TEMPLATES: readonly UseCaseTemplate[] = Object.freeze([
  {
    id: 'on-demand',
    title: 'On-Demand Connectivity',
    subtitle: 'Agile, consumption-based network services provisioned in real-time',
    icon: '⚡',
    accentColor: 'cyan',
    requirementsSummary: 'Enable rapid provisioning of network connectivity services with elastic bandwidth, automated orchestration, and pay-per-use economics. Designed for organizations that need to spin up and tear down connections dynamically based on business demand, M&A activity, or seasonal workloads.',
    considerations: [
      'Requires API-driven orchestration platform with sub-hour provisioning SLAs',
      'Bandwidth elasticity must support burst scenarios without pre-commitment penalties',
      'Integration with existing ITSM/ServiceNow workflows for change management',
      'Consider geographic coverage gaps — not all PoPs support on-demand provisioning equally',
      'Evaluate provider lock-in risk: portability of orchestration APIs and automation scripts',
      'Security policy must propagate dynamically with each new connection instantiation',
      'Metering and chargeback models need alignment with finance/procurement processes',
    ],
    architectureCharacteristics: [
      { label: 'Provisioning Speed', value: '< 1 hour', icon: '⏱' },
      { label: 'Bandwidth Elasticity', value: '50 Mbps – 10 Gbps', icon: '📊' },
      { label: 'Contract Model', value: 'Consumption-based', icon: '💳' },
      { label: 'Orchestration', value: 'API / Portal / IaC', icon: '🔗' },
      { label: 'Availability SLA', value: '99.95%+', icon: '🛡' },
      { label: 'Global Reach', value: '60+ metros', icon: '🌐' },
    ],
    applicabilityTags: ['M&A Integration', 'Seasonal Scaling', 'DR/BC Activation', 'Event-Driven', 'DevOps Pipelines', 'Hybrid Cloud Burst'],
    businessDrivers: [
      'Reduce time-to-revenue for new site activations from weeks to hours',
      'Eliminate stranded bandwidth costs through consumption-based pricing',
      'Support M&A integration timelines without long-term circuit commitments',
      'Enable infrastructure-as-code practices for network automation',
      'Provide CFO-friendly OpEx model aligned with cloud economics',
    ],
    painPoints: [
      'Legacy MPLS circuits require 45-90 day lead times for new connections',
      'Over-provisioned bandwidth at 60%+ of sites leads to wasted spend',
      'Manual provisioning workflows create bottlenecks and human error',
      'Inability to rapidly stand up DR connectivity during incidents',
      'Rigid contracts prevent adapting to changing business requirements',
    ],
    requirementChecklist: [
      { id: 'od-1', label: 'API-driven provisioning with < 60 min activation', category: 'Core', critical: true },
      { id: 'od-2', label: 'Self-service portal for authorized requestors', category: 'Core', critical: true },
      { id: 'od-3', label: 'Bandwidth scaling without service interruption', category: 'Core', critical: true },
      { id: 'od-4', label: 'Integration with Terraform / Pulumi / CloudFormation', category: 'Automation', critical: false },
      { id: 'od-5', label: 'Real-time usage metering and cost dashboards', category: 'Observability', critical: true },
      { id: 'od-6', label: 'Automated security policy propagation on connect', category: 'Security', critical: true },
      { id: 'od-7', label: 'Multi-provider redundancy for critical paths', category: 'Resilience', critical: false },
      { id: 'od-8', label: 'ServiceNow / ITSM webhook integration', category: 'Automation', critical: false },
      { id: 'od-9', label: 'Guaranteed burst capacity with committed floor', category: 'Performance', critical: false },
      { id: 'od-10', label: 'Geographic PoP coverage across all target metros', category: 'Coverage', critical: true },
    ],
    diagramNodes: [
      { label: 'Orchestration\nPortal', icon: '🎛', x: 300, y: 30, group: 'control' },
      { label: 'API\nGateway', icon: '🔗', x: 300, y: 130, group: 'control' },
      { label: 'Branch\nSite A', icon: '🏢', x: 60, y: 250, group: 'edge' },
      { label: 'Branch\nSite B', icon: '🏢', x: 180, y: 250, group: 'edge' },
      { label: 'NaaS\nFabric', icon: '🌐', x: 300, y: 250, group: 'core' },
      { label: 'Cloud\nRegion', icon: '☁️', x: 420, y: 250, group: 'cloud' },
      { label: 'Data\nCenter', icon: '🏗', x: 540, y: 250, group: 'dc' },
      { label: 'Metering\nEngine', icon: '📊', x: 480, y: 130, group: 'control' },
    ],
    diagramEdges: [[0, 1], [1, 4], [2, 4], [3, 4], [4, 5], [4, 6], [1, 7]],
    recommendedWhen: [
      'Organization is actively pursuing M&A and needs rapid integration',
      'Seasonal or event-driven workloads create highly variable bandwidth demands',
      'Cloud-first strategy requires dynamic connectivity to multiple CSPs',
      'CFO mandates shift from CapEx to OpEx for network infrastructure',
      'DevOps teams require infrastructure-as-code for network provisioning',
    ],
    notIdealWhen: [
      'All sites have stable, predictable bandwidth needs with no variability',
      'Regulatory requirements mandate dedicated physical circuits (e.g., SWIFT)',
      'Organization lacks API/automation maturity to leverage orchestration',
      'Ultra-low latency requirements (< 5ms) demand dedicated wavelengths',
      'Budget model is locked into multi-year CapEx commitments',
    ],
  },
  {
    id: 'multi-cloud',
    title: 'Multi-Cloud Connectivity',
    subtitle: 'Unified fabric connecting workloads across AWS, Azure, GCP, and private clouds',
    icon: '☁️',
    accentColor: 'violet',
    requirementsSummary: 'Architect a cloud-interconnect fabric that provides deterministic, low-latency, and policy-consistent connectivity between multiple cloud service providers, on-premises data centers, and SaaS platforms. Eliminate the complexity of managing disparate cloud networking constructs by abstracting connectivity into a unified control plane.',
    considerations: [
      'Each CSP has unique networking primitives — VPC peering, VNet, Interconnect — requiring abstraction layer',
      'Egress cost optimization is critical: cloud-to-cloud traffic can generate significant unplanned costs',
      'DNS resolution strategy must work seamlessly across cloud boundaries',
      'Identity and access management must federate consistently across all cloud environments',
      'Data sovereignty and residency requirements may constrain routing paths between regions',
      'Network segmentation policies must translate consistently across CSP-native constructs',
      'Monitoring and troubleshooting requires correlated telemetry across cloud boundaries',
    ],
    architectureCharacteristics: [
      { label: 'Cloud Providers', value: 'AWS + Azure + GCP', icon: '☁️' },
      { label: 'Interconnect Latency', value: '< 10ms cross-cloud', icon: '⏱' },
      { label: 'Segmentation', value: 'Micro-segmented', icon: '🔒' },
      { label: 'Control Plane', value: 'Unified / Abstracted', icon: '🎛' },
      { label: 'Egress Optimization', value: 'Policy-driven routing', icon: '💰' },
      { label: 'Encryption', value: 'End-to-end (MACsec/IPsec)', icon: '🛡' },
    ],
    applicabilityTags: ['Hybrid Cloud', 'Cloud Migration', 'SaaS Integration', 'Data Residency', 'Disaster Recovery', 'Platform Engineering'],
    businessDrivers: [
      'Avoid vendor lock-in by distributing workloads across best-of-breed cloud platforms',
      'Meet data residency and sovereignty requirements through flexible routing',
      'Optimize cloud egress costs through intelligent traffic engineering',
      'Enable platform engineering teams to consume network-as-a-service across clouds',
      'Support disaster recovery with cross-cloud failover capabilities',
    ],
    painPoints: [
      'Siloed cloud networking teams managing each CSP independently',
      'Inconsistent security policies across AWS Security Groups, Azure NSGs, and GCP Firewall Rules',
      'Unpredictable and escalating cloud egress charges',
      'Lack of end-to-end visibility for cross-cloud application traffic flows',
      'Manual and error-prone process for extending network policies to new cloud regions',
    ],
    requirementChecklist: [
      { id: 'mc-1', label: 'Private interconnect to AWS, Azure, and GCP (Direct Connect / ExpressRoute / Interconnect)', category: 'Core', critical: true },
      { id: 'mc-2', label: 'Unified network policy engine across all cloud environments', category: 'Security', critical: true },
      { id: 'mc-3', label: 'Cross-cloud traffic visibility with flow-level analytics', category: 'Observability', critical: true },
      { id: 'mc-4', label: 'Egress cost optimization with policy-based routing', category: 'Cost', critical: true },
      { id: 'mc-5', label: 'Automated VPC/VNet provisioning via IaC templates', category: 'Automation', critical: false },
      { id: 'mc-6', label: 'DNS resolution across cloud boundaries (hybrid DNS)', category: 'Core', critical: true },
      { id: 'mc-7', label: 'Encryption in transit (MACsec on interconnect, IPsec overlay)', category: 'Security', critical: true },
      { id: 'mc-8', label: 'Multi-region failover with automated BGP path selection', category: 'Resilience', critical: false },
      { id: 'mc-9', label: 'Cloud network compliance reporting (CIS, SOC2)', category: 'Compliance', critical: false },
      { id: 'mc-10', label: 'SaaS application direct breakout optimization', category: 'Performance', critical: false },
    ],
    diagramNodes: [
      { label: 'Cloud\nRouter', icon: '🎛', x: 300, y: 30, group: 'control' },
      { label: 'AWS\nVPC', icon: '☁️', x: 80, y: 160, group: 'cloud' },
      { label: 'Azure\nVNet', icon: '☁️', x: 300, y: 160, group: 'cloud' },
      { label: 'GCP\nVPC', icon: '☁️', x: 520, y: 160, group: 'cloud' },
      { label: 'Interconnect\nFabric', icon: '🌐', x: 300, y: 280, group: 'core' },
      { label: 'On-Prem\nDC', icon: '🏗', x: 120, y: 370, group: 'dc' },
      { label: 'Policy\nEngine', icon: '🔒', x: 480, y: 370, group: 'security' },
      { label: 'SaaS\nPlatforms', icon: '📦', x: 300, y: 370, group: 'saas' },
    ],
    diagramEdges: [[0, 1], [0, 2], [0, 3], [1, 4], [2, 4], [3, 4], [4, 5], [4, 7], [0, 6]],
    recommendedWhen: [
      'Workloads are distributed across two or more CSPs by design or acquisition',
      'Data residency requirements demand flexible, region-aware routing',
      'Cloud egress costs are a top-3 line item in infrastructure spend',
      'Platform engineering team needs self-service cloud networking',
      'Active cloud migration with phased workload movement between environments',
    ],
    notIdealWhen: [
      'Organization is committed to a single CSP with no multi-cloud strategy',
      'All workloads are SaaS-consumed with no IaaS/PaaS footprint',
      'Network team lacks cloud networking skills across multiple platforms',
      'Budget does not support private interconnects (public internet is acceptable)',
      'Application architecture is monolithic with no distributed components',
    ],
  },
  {
    id: 'sdwan',
    title: 'SD-WAN',
    subtitle: 'Software-defined branch networking with intelligent path selection and centralized policy',
    icon: '🔀',
    accentColor: 'emerald',
    requirementsSummary: 'Deploy an SD-WAN overlay across branch and campus sites to replace or augment legacy MPLS with intelligent, application-aware path selection over broadband, LTE/5G, and private circuits. Centralize network policy management while enabling local internet breakout for cloud and SaaS applications.',
    considerations: [
      'Underlay diversity is critical — at minimum dual ISP or ISP + LTE at each site for resilience',
      'Application identification and classification policies must be tuned per-customer application portfolio',
      'Legacy MPLS decommission timeline must align with SD-WAN readiness milestones per site',
      'WAN optimization (dedup, compression, FEC) requirements vary by application sensitivity',
      'Zero-touch provisioning (ZTP) maturity determines rollout velocity — test early with pilot sites',
      'Integration with existing security stack (firewalls, proxies) or plan for convergence with SASE',
      'Cellular failover costs can surprise — negotiate pooled data plans across sites upfront',
    ],
    architectureCharacteristics: [
      { label: 'Topology', value: 'Hub-spoke + mesh', icon: '🔀' },
      { label: 'Transport', value: 'MPLS + Broadband + LTE', icon: '📡' },
      { label: 'Path Selection', value: 'Application-aware', icon: '🧠' },
      { label: 'Deployment', value: 'Zero-touch (ZTP)', icon: '📦' },
      { label: 'Encryption', value: 'AES-256 IPsec overlay', icon: '🔒' },
      { label: 'Management', value: 'Centralized orchestrator', icon: '🎛' },
    ],
    applicabilityTags: ['Branch Modernization', 'MPLS Migration', 'Cloud Breakout', 'Retail/Distributed', 'Cost Optimization', 'WAN Simplification'],
    businessDrivers: [
      'Reduce WAN costs by supplementing or replacing expensive MPLS with broadband',
      'Improve application performance through intelligent, real-time path selection',
      'Accelerate new site deployments with zero-touch provisioning',
      'Enable direct cloud/SaaS breakout to improve user experience and reduce backhaul',
      'Centralize network policy management across hundreds of distributed sites',
    ],
    painPoints: [
      'MPLS costs consuming 40-60% of total network budget with limited bandwidth growth',
      'Poor SaaS/cloud performance due to backhauling traffic through central data centers',
      'New site provisioning takes 60-90 days due to circuit lead times and manual config',
      'No application-level visibility into WAN performance metrics',
      'Branch firewall sprawl creating inconsistent security posture across locations',
    ],
    requirementChecklist: [
      { id: 'sd-1', label: 'Centralized orchestrator with single-pane management', category: 'Core', critical: true },
      { id: 'sd-2', label: 'Application-aware routing with real-time path selection', category: 'Core', critical: true },
      { id: 'sd-3', label: 'Support for broadband, MPLS, and LTE/5G transport simultaneously', category: 'Core', critical: true },
      { id: 'sd-4', label: 'Zero-touch provisioning for new site deployments', category: 'Operations', critical: true },
      { id: 'sd-5', label: 'Local internet breakout with security policy enforcement', category: 'Security', critical: true },
      { id: 'sd-6', label: 'WAN optimization: FEC, packet duplication, jitter buffering', category: 'Performance', critical: false },
      { id: 'sd-7', label: 'Segmentation (VRF-lite or VLAN) for traffic isolation', category: 'Security', critical: false },
      { id: 'sd-8', label: 'Integration with cloud gateways (AWS TGW, Azure vWAN)', category: 'Cloud', critical: false },
      { id: 'sd-9', label: 'Real-time application performance SLA monitoring', category: 'Observability', critical: true },
      { id: 'sd-10', label: 'Dual-CPE or HA appliance option for critical sites', category: 'Resilience', critical: false },
    ],
    diagramNodes: [
      { label: 'SD-WAN\nOrchestrator', icon: '🎛', x: 300, y: 20, group: 'control' },
      { label: 'Hub\nGateway', icon: '🏗', x: 300, y: 140, group: 'core' },
      { label: 'Branch\nCPE 1', icon: '🏢', x: 60, y: 280, group: 'edge' },
      { label: 'Branch\nCPE 2', icon: '🏢', x: 200, y: 280, group: 'edge' },
      { label: 'Branch\nCPE 3', icon: '🏢', x: 400, y: 280, group: 'edge' },
      { label: 'Branch\nCPE 4', icon: '🏢', x: 540, y: 280, group: 'edge' },
      { label: 'Cloud\nGateway', icon: '☁️', x: 120, y: 140, group: 'cloud' },
      { label: 'SaaS\nBreakout', icon: '🌐', x: 480, y: 140, group: 'saas' },
    ],
    diagramEdges: [[0, 1], [1, 2], [1, 3], [1, 4], [1, 5], [0, 6], [0, 7], [2, 6], [5, 7]],
    recommendedWhen: [
      'Organization has 20+ branch/retail/campus sites with WAN connectivity',
      'MPLS costs are disproportionate to bandwidth delivered',
      'SaaS adoption (O365, Salesforce, etc.) is degraded by centralized backhauling',
      'Rapid site deployment capability is a business requirement',
      'Network team is ready to shift from CLI-driven to policy-driven management',
    ],
    notIdealWhen: [
      'Fewer than 5 sites with stable, low-bandwidth requirements',
      'All applications are hosted on-premises with no cloud/SaaS dependencies',
      'Regulatory environment prohibits internet transport for sensitive traffic',
      'Organization has recently signed long-term MPLS contracts with heavy ETFs',
      'No broadband availability at majority of site locations',
    ],
  },
  {
    id: 'sase',
    title: 'SASE',
    subtitle: 'Converged networking and security-as-a-service delivered from the cloud edge',
    icon: '🛡',
    accentColor: 'rose',
    requirementsSummary: 'Converge SD-WAN, Secure Web Gateway (SWG), Cloud Access Security Broker (CASB), Zero Trust Network Access (ZTNA), and Firewall-as-a-Service (FWaaS) into a unified, cloud-delivered platform. Eliminate the branch security appliance stack by shifting enforcement to globally distributed PoPs closest to users and workloads.',
    considerations: [
      'SASE is a journey, not a single deployment — plan for phased convergence of networking and security',
      'Evaluate single-vendor vs. best-of-breed (SD-WAN + SSE) architecture tradeoffs carefully',
      'User experience monitoring is essential — SASE changes traffic paths and introduces new hops',
      'Existing security tool contracts and amortization schedules affect migration timeline',
      'Remote/hybrid workforce requirements may prioritize ZTNA and SWG over SD-WAN initially',
      'Data Loss Prevention (DLP) policies need to be mapped from existing tools to SASE platform',
      'Certificate management for TLS inspection at scale requires careful planning and exceptions',
    ],
    architectureCharacteristics: [
      { label: 'Architecture', value: 'Cloud-native SSE + SD-WAN', icon: '🏗' },
      { label: 'Zero Trust', value: 'Identity-centric ZTNA', icon: '🔐' },
      { label: 'Inspection', value: 'TLS 1.3 at line rate', icon: '🔍' },
      { label: 'PoP Coverage', value: '150+ global locations', icon: '🌐' },
      { label: 'Policy Model', value: 'User + App + Device context', icon: '📋' },
      { label: 'DLP', value: 'Inline + API-based', icon: '🛡' },
    ],
    applicabilityTags: ['Zero Trust', 'Remote Workforce', 'Security Consolidation', 'Cloud-First', 'Compliance', 'Branch Simplification'],
    businessDrivers: [
      'Consolidate 5-8 security point products into a unified cloud-delivered platform',
      'Enable zero trust access for hybrid/remote workforce without VPN complexity',
      'Reduce branch hardware footprint and associated maintenance/refresh costs',
      'Achieve consistent security posture regardless of user location or device',
      'Meet compliance requirements (NIST, ISO 27001, SOC2) with unified audit trail',
    ],
    painPoints: [
      'Branch security stack (FW, proxy, IDS/IPS) creates operational complexity and cost',
      'VPN infrastructure cannot scale for permanent hybrid workforce',
      'Inconsistent security policies between on-premises and remote users',
      'Shadow IT and unsanctioned SaaS usage lack visibility and control',
      'Security incidents take too long to investigate due to fragmented logging',
    ],
    requirementChecklist: [
      { id: 'sa-1', label: 'Cloud-delivered Secure Web Gateway (SWG) with TLS inspection', category: 'Core', critical: true },
      { id: 'sa-2', label: 'Zero Trust Network Access (ZTNA) replacing legacy VPN', category: 'Core', critical: true },
      { id: 'sa-3', label: 'Cloud Access Security Broker (CASB) for SaaS visibility and control', category: 'Core', critical: true },
      { id: 'sa-4', label: 'Firewall-as-a-Service (FWaaS) with L3-L7 inspection', category: 'Core', critical: true },
      { id: 'sa-5', label: 'SD-WAN integration (single-vendor or validated best-of-breed)', category: 'Network', critical: true },
      { id: 'sa-6', label: 'Data Loss Prevention (DLP) — inline and API-based', category: 'Security', critical: false },
      { id: 'sa-7', label: 'Digital Experience Monitoring (DEM) for end-user visibility', category: 'Observability', critical: false },
      { id: 'sa-8', label: 'Identity provider integration (Okta, Azure AD, Ping)', category: 'Identity', critical: true },
      { id: 'sa-9', label: 'Unified logging and SIEM/SOAR integration', category: 'Security', critical: false },
      { id: 'sa-10', label: 'Browser isolation for high-risk web categories', category: 'Security', critical: false },
    ],
    diagramNodes: [
      { label: 'SASE\nCloud', icon: '🛡', x: 300, y: 30, group: 'core' },
      { label: 'SWG', icon: '🌐', x: 120, y: 140, group: 'security' },
      { label: 'ZTNA', icon: '🔐', x: 260, y: 140, group: 'security' },
      { label: 'CASB', icon: '📋', x: 400, y: 140, group: 'security' },
      { label: 'FWaaS', icon: '🔥', x: 540, y: 140, group: 'security' },
      { label: 'Remote\nUsers', icon: '👤', x: 60, y: 280, group: 'edge' },
      { label: 'Branch\nSites', icon: '🏢', x: 220, y: 280, group: 'edge' },
      { label: 'Cloud\nApps', icon: '☁️', x: 380, y: 280, group: 'cloud' },
      { label: 'Private\nApps', icon: '🏗', x: 540, y: 280, group: 'dc' },
    ],
    diagramEdges: [[0, 1], [0, 2], [0, 3], [0, 4], [5, 1], [5, 2], [6, 0], [7, 3], [8, 2], [8, 4]],
    recommendedWhen: [
      'Organization is pursuing zero trust architecture transformation',
      'Hybrid/remote workforce exceeds 30% of total employees',
      'Security appliance refresh cycle is approaching (3+ tools EOL within 18 months)',
      'Cloud and SaaS adoption exceeds 50% of application portfolio',
      'CISO mandate to consolidate security vendors and reduce tool sprawl',
    ],
    notIdealWhen: [
      'All users are on-premises with no remote work policy',
      'Security tools were recently purchased with 3+ years remaining on contracts',
      'Application portfolio is 90%+ on-premises with minimal SaaS adoption',
      'Organization requires air-gapped or fully offline network segments',
      'Regulatory environment requires all traffic inspection to remain on-premises',
    ],
  },
]);

export { TEMPLATES };
